spring:
  datasource:
    url: jdbc:mysql://188.131.133.149/sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 199720Jiang.
  jpa:
    show-sql: true
    open-in-view: true
server:
  servlet:
    context-path: /piloteer
  port: 8080